### ISSUE TITLE
ChromeDriver installation error with latest version 107.0.2

### ISSUE THREAD

**Issue by adtakle** [giggio/node-chromedriver#395]
When I run `npm install chromedriver@latest`, I am seeing the following error:
ChromeDriver binary exists. Validating...
ChromeDriver is already available at '<location>\Local\Temp\107.0.5304.62\chromedriver\chromedriver.exe'.
ChromeDriver installation failed TypeError: fs.rmSync is not a function
    at copyIntoPlace (<location>\node_modules\chromedriver\install.js:312:6)
    at install (<location>\node_modules\chromedriver\install.js:73:11)

I'm using node `v16.14.2`. When I downgrade to chromedriver version `106.0.1`, I am no longer seeing this installation failure.

**Comment by giggio** [comment]
@adtakle I can't repro it, I just tested it with this exact Node.js version (`16.14.2`).
`fs.rmSync` is available since Node.js 14: https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fs_rmsync_path_options
Github actions [is building fine](https://github.com/giggio/node-chromedriver/actions/workflows/build.yml) in all supported Node.js versions.
This was added recently, that is why you are not seeing it in older versions.
I need repro steps.

**Comment by kmstumpff** [comment]
We had this issue today and we solved it by updating the node version in out package.json. We had `"node": "^14.7.0"` and after updating it to `"node": "^16.16.0"`, chromedriver installed correctly.

**Comment by giggio** [comment]
Version 14.7.0 is not LTS and is no longer supported. It needs to migrate to an LTS version, which starts for 14 in 14.15.0: [nodejs.org/en/blog/release/v14.15.0](https://nodejs.org/en/blog/release/v14.15.0/)
