### ISSUE TITLE
Can we please change the runtime engine back to node 14?

### ISSUE THREAD

**Issue by jamesmortensen** [giggio/node-chromedriver#422]
Our organization uses WebdriverIO.  We're still stuck on sync mode, which means we're stuck on Node 14.  Migrating is taking some time, and we didn't expect the runtime engine for node-chromedriver to change since all the module does is install chromedriver binaries.

https://github.com/giggio/node-chromedriver/blob/9ad4b0db0eb1d24f5877ddfd2d78b591f12f9a0b/package.json#L44

Is it possible to eliminate this requirement?  We're not expecting you to provide support if something breaks, but adding the required engine breaks functionality that I believe would continue to work for quite some time beyond the life of Node 14.  

Please let me know what's possible.  Thank you!

**Comment by giggio** [comment]
@jamesmortensen The problem is that I've been questioned when I changed something that broke on older versions, people told me that the package did not specify the versions it supported. Since then, I've aligned the `node` field in `package.json` with the support for this package, which is: it supports supported Node.js versions.
Saying it supports 14 without actually supporting it might cause more damage. For example, the GH Actions don't run against version 14. Something might break and nobody would notice.
I don't use WebdriverIO, can you give me more details?

**Comment by jamesmortensen** [comment]
Hi @giggio I understand where you're coming from.  Managing open source repos is tough. We worked around the issue by uninstalling the module and just using the chromedriver installed by GitHub Actions by default.  

Another way others could solve the problem is make a fork of node-chromium, change the required node engine, and then import the package in package.json directly from GitHub.

To answer your question, WebdriverIO 7 relied on a module called fibers, which allowed developers and testers to write async code without having to use async/await.  Fibers relied on undocumented, internal Node APIs, and the upgrade from 14 to 16 broke fibers.

In order to update from Node14 to Node16, anyone who was using WebdriverIO with fibers needed to modify all their code so that they added in all of the missing async/awaits that fibers would add in at runtime dynamically.

Thanks for your reply and explanation.  I'll go ahead and close the issue.
