### ISSUE TITLE
win64 nor surport?

### ISSUE THREAD

**Issue by 5j2f** [giggio/node-chromedriver#66]
warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
974 verbose stack Error: chromedriver@2.24.1 install: `node install.js`
974 verbose stack Exit status 1

**Comment by giggio** [comment]
Yest, is is supported. Can you post your logs, please? What Windows, node and npm version are you on?

**Comment by singcl** [comment]
warn : Not compatible with your operating system or architecture: fsevents@1.0.14.
this is error log.

[npm-debug.txt](https://github.com/giggio/node-chromedriver/files/491528/npm-debug.txt)

**Comment by giggio** [comment]
Just tried with the same node version, I can't repro it. You can see the Windows Version and NPM version:
<img width="973" alt="node4" src="https://cloud.githubusercontent.com/assets/334958/18845069/82f5beb6-83f6-11e6-97d1-ecce0dc1e8c2.PNG">

For myself:

````powershell
"$(([System.Environment]::OSVersion).VersionString) - $(if ([System.Environment]::Is64BitOperatingSystem) { '64' } else { '32' } ) bits"
````

Same thing for newer node and npm versions. I tried it with node 4.2.0 and npm 3.3.8, and it worked, and with node 6.2.0 and npm 3.8.9.

I am not sure why you are getting this warning with fsevents, and if it is related to the failure or not. In the past there was a bug on npm itself regarding optional dependencies, and we had to install using `--no-optional` otherwise it would fail. But this bug was fixed 6 months or so ago.

You could try to `npm install chromedriver --no-optional`, and see if it works.

I am closing this issue as a no repro, as the steps provided are not enough to repro, if you can consistently repro, let us know and we will reopen it.
