### ISSUE TITLE
If the file is already downloaded do not download it again

### ISSUE THREAD

**Issue by royriojas** [giggio/node-chromedriver#72]
Hi thanks for the awesome wrapper. Would you consider to check if the file is already downloaded to avoid redownloading all the time? something similar to this?

https://github.com/Medium/phantomjs/blob/master/install.js#L419

Or, would you be open to accept a PR to add such functionality?

**Comment by giggio** [comment]
How would you guarantee that the file is not corrupt and is not from a different version?

**Comment by royriojas** [comment]
It seems that phantomjs does calculating the checksums, do we have the checksum of the chromedriver packages?

**Comment by giggio** [comment]
I don't think so, I just looked at http://chromedriver.storage.googleapis.com and did not find any.

**Comment by royriojas** [comment]
can't we try to calculate the checksum? I know it might be hassle to maintain, but having that will allow us to do something similar to what `phantom` does.

**Comment by giggio** [comment]
@royriojas we could. A PR is welcome.

**Comment by munir131** [comment]
@royriojas If file already exist then we can use `chromedriver --version` to detect version.
![image](https://user-images.githubusercontent.com/6319375/38257435-d97dd8b8-377d-11e8-8527-a30a92cf5047.png)

**Comment by mitar** [comment]
As described in #170, I also thin that downloading should be done and cached into `~/.cache` or somewhere like that, and not `node_modules`, so that one can quickly recreate `node_modules` without having to download stuff.

This is how [Cypress NPM wrapper](https://docs.cypress.io/guides/guides/continuous-integration.html#Caching-the-Cypress-Binary) does it and it works great. They download a binary into `~/.cache` and then NPM wrapper just installs it from there.

**Comment by giggio** [comment]
Done on #183.

**Comment by giggio** [comment]
I just tested and the solution does not work. I am reopening it.

**Comment by giggio** [comment]
Ok, now it is fixed. I'll release it in a minute.
